"""任务中心仓储接口（协调 runs + test_plan）。

task-center 是横切展示/协调域：既协调 legacy 执行任务队列
（`app.tasks.manager`，提交/查询/停止/删除/重跑/列表），也协调定时任务
（test_plan_schedules）。这些方法均属 task_center 域对底层 legacy 队列/计划
存储的「协调」，不把任务搬移到其他域。
"""
from __future__ import annotations

from typing import Protocol


class TaskCenterRepository(Protocol):
    """任务中心协调接口。"""

    # ── exec-task（执行任务）── ────────────────────────────
    def stop_tasks(self, ids: list) -> dict: ...
    def delete_tasks(self, ids: list) -> dict: ...
    def rerun_task(self, task_id: str) -> dict: ...
    async def submit_task(self, name: str, payload: dict): ...
    def get_task(self, task_id: str): ...
    def list_raw_tasks(self, limit: int) -> list: ...
    def list_tasks(self) -> list: ...

    # ── schedule（定时任务）── ─────────────────────────────
    def switch_schedules(self, ids: list) -> dict: ...
    def enable_schedules(self, ids: list, enable: bool) -> dict: ...
    def delete_schedules(self, ids: list) -> dict: ...
    def update_schedule_cron(self, ids: list, cron: str) -> dict: ...


__all__ = ["TaskCenterRepository"]
