"""前端兼容仓储接口（委托 apitest）。"""
from __future__ import annotations

from typing import Optional, Protocol


class FrontendApiRepository(Protocol):
    """前端兼容数据访问接口（TestPilot 兼容管理入口）。"""

    # ── 导入 ─────────────────────────────────────────────
    def import_from_postman(self, data: dict) -> dict: ...
    def import_from_swagger(self, data: dict) -> dict: ...

    # ── 接口定义 ─────────────────────────────────────────
    def list_api_definitions(self, **kwargs) -> list: ...
    def create_api_definition(self, **kwargs) -> dict: ...
    def get_api_definition(self, def_id: str) -> Optional[dict]: ...
    def update_api_definition(self, def_id: str, **kwargs) -> Optional[dict]: ...
    def delete_api_definition(self, def_id: str, permanent: bool = False) -> bool: ...
    def list_trash_definitions(self, limit: int = 100) -> list: ...
    def restore_definition(self, def_id: str) -> bool: ...

    # ── 接口用例 ─────────────────────────────────────────
    def list_api_test_cases(self, **kwargs) -> list: ...
    def create_api_test_case(self, **kwargs) -> dict: ...
    def get_api_test_case(self, case_id: str) -> Optional[dict]: ...
    def update_api_test_case(self, case_id: str, **kwargs) -> Optional[dict]: ...
    def delete_api_test_case(self, case_id: str, permanent: bool = False) -> bool: ...
    def restore_case(self, case_id: str) -> bool: ...

    # ── 场景 ─────────────────────────────────────────────
    def list_scenarios(self, **kwargs) -> list: ...
    def create_scenario(self, **kwargs) -> dict: ...
    def execute_scenario(self, scenario_id: str) -> dict: ...
    def get_scenario(self, scenario_id: str) -> Optional[dict]: ...
    def update_scenario(self, scenario_id: str, **kwargs) -> Optional[dict]: ...
    def delete_scenario(self, scenario_id: str, permanent: bool = False) -> bool: ...
    def list_trash_scenarios(self, limit: int = 100) -> list: ...
    def restore_scenario(self, scenario_id: str) -> bool: ...

    # ── Mock ─────────────────────────────────────────────
    def list_mock_services(self, **kwargs) -> list: ...
    def create_mock_service(self, **kwargs) -> dict: ...
    def get_mock_service(self, mock_id: str) -> Optional[dict]: ...
    def update_mock_service(self, mock_id: str, **kwargs) -> Optional[dict]: ...
    def delete_mock_service(self, mock_id: str, permanent: bool = False) -> bool: ...


__all__ = ["FrontendApiRepository"]
