"""脚本聚合仓储接口（Repository Port）。"""
from __future__ import annotations

from typing import List, Optional, Protocol

from app.domain.script.domain.entities.script import Script


class ScriptRepository(Protocol):
    """脚本聚合仓储契约。"""

    def register(self, script: Script) -> Script: ...
    def get(self, script_id: str) -> Optional[Script]: ...
    def list(self, status: Optional[str] = None, search: Optional[str] = None,
             limit: int = 100, offset: int = 0) -> List[Script]: ...
    def update(self, script: Script) -> Optional[Script]: ...
    def delete(self, script_id: str) -> bool: ...
    def record_execution(self, script_id: str, success: bool, duration: float,
                         error_type: str, error_message: str,
                         locator_failures: Optional[list]) -> dict: ...
    def list_executions(self, script_id: str, limit: int = 20) -> list: ...
    def stats(self) -> dict: ...


__all__ = ["ScriptRepository"]
