# -*- coding: utf-8 -*-
"""app.cases.management 包（由原 management.py 拆分，对外符号保持一致）。"""

from app.cases.management._base import (
    CHANGE_CREATED,
    CHANGE_DELETED,
    CHANGE_EXPORTED,
    CHANGE_IMPORTED,
    CHANGE_RESTORED,
    CHANGE_REVIEW_APPROVED,
    CHANGE_REVIEW_REJECTED,
    CHANGE_REVIEW_SUBMITTED,
    CHANGE_UPDATED,
    CHANGE_VERSION_CREATED,
    CHANGE_VERSION_ROLLED_BACK,
    REVIEW_STATUS_APPROVED,
    REVIEW_STATUS_NEED_REVISE,
    REVIEW_STATUS_PENDING,
    REVIEW_STATUS_REJECTED,
    _create_version,
    _gen_id,
    _get_base_case,
    _get_base_conn,
    _get_conn,
    _init_management_tables,
    _list_base_cases,
    _now,
    _record_change,
    _update_base_case,
    logger,
)
from app.cases.management.dependencies import (
    add_case_dependency,
    list_case_dependencies,
    remove_case_dependency,
)
from app.cases.management.full_info import get_case_full_info
from app.cases.management.import_export import (
    export_cases_excel,
    export_cases_mindmap,
    import_cases_from_excel,
    import_cases_from_xmind,
)
from app.cases.management.mindmap import get_case_mindmap, invalidate_mindmap_cache
from app.cases.management.relations import (
    add_case_relation,
    list_case_relations,
    remove_case_relation,
)
from app.cases.management.requirements import (
    add_case_requirement,
    list_case_requirements,
    remove_case_requirement,
)
from app.cases.management.reviews import (
    approve_review,
    get_case_reviews,
    reject_review,
    submit_for_review,
)
from app.cases.management.trash import list_trash_cases, purge_case, restore_case, soft_delete_case
from app.cases.management.versions import (
    count_case_changes,
    get_case_version,
    list_case_changes,
    list_case_versions,
    rollback_case,
)

__all__ = [
    '_get_conn',
    '_now',
    '_gen_id',
    '_record_change',
    '_create_version',
    '_init_management_tables',
    '_get_base_conn',
    '_get_base_case',
    '_update_base_case',
    '_list_base_cases',
    'logger',
    'REVIEW_STATUS_PENDING',
    'REVIEW_STATUS_APPROVED',
    'REVIEW_STATUS_REJECTED',
    'REVIEW_STATUS_NEED_REVISE',
    'CHANGE_CREATED',
    'CHANGE_UPDATED',
    'CHANGE_DELETED',
    'CHANGE_RESTORED',
    'CHANGE_VERSION_CREATED',
    'CHANGE_VERSION_ROLLED_BACK',
    'CHANGE_REVIEW_SUBMITTED',
    'CHANGE_REVIEW_APPROVED',
    'CHANGE_REVIEW_REJECTED',
    'CHANGE_IMPORTED',
    'CHANGE_EXPORTED',
    'add_case_relation',
    'remove_case_relation',
    'list_case_relations',
    'invalidate_mindmap_cache',
    'get_case_mindmap',
    'export_cases_excel',
    'export_cases_mindmap',
    'import_cases_from_excel',
    'import_cases_from_xmind',
    'submit_for_review',
    'approve_review',
    'reject_review',
    'get_case_reviews',
    'add_case_dependency',
    'remove_case_dependency',
    'list_case_dependencies',
    'soft_delete_case',
    'restore_case',
    'list_trash_cases',
    'purge_case',
    'list_case_versions',
    'get_case_version',
    'rollback_case',
    'list_case_changes',
    'count_case_changes',
    'add_case_requirement',
    'remove_case_requirement',
    'list_case_requirements',
    'get_case_full_info',
]
