"""消息聚合仓储接口（Repository Port）。"""
from __future__ import annotations

from typing import List, Optional, Protocol

from app.domain.message.domain.entities.notification import Notification
from app.domain.message.domain.entities.robot import Robot


class RobotRepository(Protocol):
    """机器人聚合仓储契约。"""
    def list_robots(self, project_id: str = "") -> List[Robot]: ...
    def get_robot(self, robot_id: str) -> Optional[Robot]: ...
    def create_robot(self, robot: Robot) -> Robot: ...
    def update_robot(self, robot_id: str, data: dict) -> bool: ...
    def delete_robot(self, robot_id: str) -> bool: ...
    def set_robot_enable(self, robot_id: str, enable: bool) -> bool: ...


class NotificationRepository(Protocol):
    """通知聚合仓储契约。"""
    def create_notification(self, notification: Notification) -> str: ...
    def list_notifications(self, receiver: str = "", status: str = "",
                           type_: str = "", resource_type: str = "",
                           keyword: str = "", project_id: str = "",
                           limit: int = 50, offset: int = 0) -> List[Notification]: ...
    def count_notifications(self, receiver: str = "", status: str = "",
                            resource_type: str = "") -> int: ...
    def set_read(self, notification_id: str) -> bool: ...
    def set_read_all(self, receiver: str = "", resource_type: str = "") -> int: ...


__all__ = ["RobotRepository", "NotificationRepository"]
