"""环境聚合仓储接口（Repository Port）。"""
from __future__ import annotations

from typing import List, Optional, Protocol

from app.domain.environment.domain.entities.environment import Environment


class EnvironmentRepository(Protocol):
    """环境聚合仓储契约。"""

    def create(self, env: Environment) -> Environment: ...
    def get(self, env_id: str) -> Optional[Environment]: ...
    def list(self, search: str = "", status: str = "",
             env_type: str = "") -> List[Environment]: ...
    def update(self, env: Environment) -> Optional[Environment]: ...
    def delete(self, env_id: str, permanent: bool = False) -> bool: ...
    def list_trash(self) -> List[dict]: ...
    def restore(self, env_id: str) -> bool: ...
    def trash(self, env_id: str) -> bool: ...
    def purge(self, env_id: str) -> bool: ...
    def create_alert(self, env_id: str, env_name: str, level: str,
                     message: str, detail: str = "") -> dict: ...
    def list_alerts(self, limit: int = 50, level: str = "") -> list: ...
    def resolve_alert(self, alert_id: str) -> bool: ...
    def get_stats(self) -> dict: ...


__all__ = ["EnvironmentRepository"]
