"""误报规则聚合仓储接口。"""
from __future__ import annotations

from typing import List, Protocol

from app.domain.fake_error.domain.entities.error_rule import FakeErrorRule


class FakeErrorRepository(Protocol):
    """误报规则聚合仓储契约。"""
    def next_id(self) -> str: ...
    def save(self, rule: FakeErrorRule) -> FakeErrorRule: ...
    def list(self, project_id: str = "") -> List[FakeErrorRule]: ...
    def delete(self, rule_id: str) -> bool: ...
    def update_enable(self, rule_ids: List[str], enable: bool) -> None: ...
    def get_enabled_count(self, project_id: str = "") -> int: ...

__all__ = ["FakeErrorRepository"]
