"""用户视图聚合仓储接口。"""
from __future__ import annotations

from typing import List, Optional, Protocol

from app.domain.user_view.domain.entities.user_view import UserView


class UserViewRepository(Protocol):
    def next_id(self) -> str: ...
    def save(self, view: UserView) -> UserView: ...
    def get(self, view_id: str) -> Optional[UserView]: ...
    def list_by_type(self, view_type: str, scope_id: str = "") -> List[UserView]: ...
    def delete(self, view_id: str) -> bool: ...

__all__ = ["UserViewRepository"]
