"""接口测试聚合仓储接口（Repository Port）。

仅在 domain 层定义、由 infrastructure 实现。应用层依赖此接口而非具体
实现，便于测试替换（内存仓储）与多存储切换。

仓储粒度为"聚合"：每个聚合及其子实体/值对象作为一个整体被读写。
按聚合根拆分为三组协议：ApiDefinitionRepository / ApiCaseRepository /
ScenarioRepository。
"""
from __future__ import annotations

from typing import List, Optional, Protocol, Tuple

from app.domain.apitest.domain.entities.api_case import ApiCase
from app.domain.apitest.domain.entities.api_definition import ApiDefinition
from app.domain.apitest.domain.entities.mock import ApiMock
from app.domain.apitest.domain.entities.scenario import Scenario


class ApiDefinitionRepository(Protocol):
    """接口定义聚合仓储契约。"""

    def next_id(self) -> str: ...

    def save(self, definition: ApiDefinition) -> ApiDefinition: ...

    def update(self, definition: ApiDefinition) -> bool: ...

    def find_by_id(self, definition_id: str,
                   include_deleted: bool = False) -> Optional[ApiDefinition]: ...

    def soft_delete(self, definition_id: str) -> bool: ...

    def restore(self, definition_id: str) -> bool: ...

    def list_trash(self, project_id: str = "",
                   limit: int = 100) -> Tuple[List[ApiDefinition], int]: ...

    def list(self, *, keyword: str = "", project_id: str = "",
             limit: int = 100, offset: int = 0,
             include_latest_only: bool = True,
             protocols: Optional[list] = None,
             module_ids: Optional[list] = None) -> Tuple[List[ApiDefinition], int]: ...

    def count(self, project_id: str = "", **kwargs) -> int: ...

    def record_version(self, definition_id: str, version: str = "",
                       operator: str = "") -> Optional[dict]: ...

    def list_versions(self, ref_id: str) -> list: ...


class ApiCaseRepository(Protocol):
    """接口用例聚合仓储契约。"""

    def next_id(self) -> str: ...

    def save(self, case: ApiCase) -> ApiCase: ...

    def update(self, case: ApiCase) -> bool: ...

    def find_by_id(self, case_id: str,
                   include_deleted: bool = False) -> Optional[ApiCase]: ...

    def soft_delete(self, case_id: str) -> bool: ...

    def restore(self, case_id: str) -> bool: ...

    def list_trash(self, project_id: str = "",
                   limit: int = 100) -> Tuple[List[ApiCase], int]: ...

    def list(self, *, keyword: str = "", project_id: str = "",
             api_definition_id: str = "",
             limit: int = 100, offset: int = 0) -> Tuple[List[ApiCase], int]: ...

    def count(self, project_id: str = "", **kwargs) -> int: ...


class ScenarioRepository(Protocol):
    """接口场景聚合仓储契约。"""

    def next_id(self) -> str: ...

    def save(self, scenario: Scenario) -> Scenario: ...

    def update(self, scenario: Scenario) -> bool: ...

    def find_by_id(self, scenario_id: str,
                   include_deleted: bool = False) -> Optional[Scenario]: ...

    def soft_delete(self, scenario_id: str) -> bool: ...

    def restore(self, scenario_id: str) -> bool: ...

    def list_trash(self, project_id: str = "",
                   limit: int = 100) -> Tuple[List[Scenario], int]: ...

    def list(self, *, keyword: str = "", project_id: str = "",
             limit: int = 100, offset: int = 0) -> Tuple[List[Scenario], int]: ...

    def count(self, project_id: str = "", **kwargs) -> int: ...


class MockRepository(Protocol):
    """Mock 服务聚合仓储契约。"""

    def next_id(self) -> str: ...

    def save(self, mock: "ApiMock") -> "ApiMock": ...

    def update(self, mock: "ApiMock") -> bool: ...

    def find_by_id(self, mock_id: str,
                   include_deleted: bool = False) -> Optional["ApiMock"]: ...

    def soft_delete(self, mock_id: str) -> bool: ...

    def restore(self, mock_id: str) -> bool: ...

    def purge(self, mock_id: str) -> bool: ...

    def list_trash(self, project_id: str = "",
                   limit: int = 100) -> Tuple[List["ApiMock"], int]: ...

    def list(self, *, keyword: str = "", project_id: str = "",
             limit: int = 100, offset: int = 0) -> Tuple[List["ApiMock"], int]: ...

    def count(self, project_id: str = "", **kwargs) -> int: ...

    def count_trash(self, project_id: str = "") -> int: ...
