"""工作流状态聚合仓储接口。"""
from __future__ import annotations

from typing import List, Optional, Protocol

from app.domain.workflow.domain.entities.workflow_status import WorkflowStatus


class WorkflowRepository(Protocol):
    def next_id(self) -> str: ...
    def save(self, status: WorkflowStatus) -> WorkflowStatus: ...
    def get(self, status_id: str) -> Optional[WorkflowStatus]: ...
    def list(self, scope_type: str, scope_id: str, scene: str) -> List[WorkflowStatus]: ...
    def delete(self, status_id: str) -> bool: ...
    def sort(self, status_ids: List[str]) -> bool: ...
    def update_flows(self, status_id: str, target_ids: List[str]) -> bool: ...
    def seed_defaults(self, scope_type: str, scope_id: str, scene: str) -> List[WorkflowStatus]: ...

__all__ = ["WorkflowRepository"]
