"""组织/成员/认证聚合仓储接口（Repository Port）。

仅在 domain 层定义、由 infrastructure 实现。应用层依赖此接口而非具体
实现，便于测试替换（内存仓储）与多存储切换。仓储粒度为"聚合"：每个聚合
作为一个整体被读取/保存，保证事务一致性。
"""
from __future__ import annotations

from typing import List, Optional, Protocol, Tuple

from app.domain.identity.domain.entities.invitation import Invitation
from app.domain.identity.domain.entities.organization import Organization
from app.domain.identity.domain.entities.role import Role
from app.domain.identity.domain.entities.user import User


class UserRepository(Protocol):
    """用户聚合仓储契约（对接 AuthRepo）。"""

    def next_id(self) -> str: ...

    def save(self, user: User) -> User: ...

    def update(self, user: User) -> Optional[User]: ...

    def find_by_id(self, user_id: str) -> Optional[User]: ...

    def find_by_username(self, username: str) -> Optional[User]: ...

    def list(self, search: str = "", limit: int = 100, offset: int = 0) -> Tuple[List[User], int]: ...

    def delete(self, user_id: str) -> bool: ...

    def change_password(self, user_id: str, new_password: str) -> bool: ...


class OrganizationRepository(Protocol):
    """组织聚合仓储契约（对接 OrganizationRepo）。"""

    def next_id(self) -> str: ...

    def save(self, org: Organization) -> Organization: ...

    def update(self, org: Organization) -> Optional[Organization]: ...

    def persist_member_change(self, org: Organization, user_id: str, role: str) -> None: ...

    def find_by_id(self, org_id: str) -> Optional[Organization]: ...

    def find_by_name(self, name: str) -> Optional[Organization]: ...

    def list(self, search: str = "", status: str = "", limit: int = 100,
             offset: int = 0) -> Tuple[List[Organization], int]: ...


class RoleRepository(Protocol):
    """角色/用户组聚合仓储契约（对接 UserGroupRepo）。"""

    def next_id(self) -> str: ...

    def save(self, role: Role) -> Role: ...

    def update(self, role: Role) -> Optional[Role]: ...

    def find_by_id(self, role_id: str) -> Optional[Role]: ...

    def find_by_name(self, name: str) -> Optional[Role]: ...

    def list(self, group_type: str = "SYSTEM", limit: int = 100,
             offset: int = 0) -> Tuple[List[Role], int]: ...

    def delete(self, role_id: str) -> bool: ...


class InvitationRepository(Protocol):
    """邀请聚合仓储契约（对接 InvitationRepo）。"""

    def next_id(self) -> str: ...

    def save(self, inv: Invitation) -> Invitation: ...

    def find_by_invite_id(self, invite_id: str) -> Optional[Invitation]: ...

    def mark_used(self, invite_id: str) -> bool: ...

    def is_valid(self, invite_id: str) -> bool: ...
