"""项目版本聚合仓储接口。"""
from __future__ import annotations

from typing import List, Optional, Protocol

from app.domain.project_version.domain.entities.project_version import ProjectVersion


class ProjectVersionRepository(Protocol):
    def next_id(self) -> str: ...
    def save(self, version: ProjectVersion) -> ProjectVersion: ...
    def get(self, version_id: str) -> Optional[ProjectVersion]: ...
    def list_by_project(self, project_id: str, keyword: str = "") -> List[ProjectVersion]: ...
    def delete(self, version_id: str) -> bool: ...
    def clear_project_latest(self, project_id: str, exclude_id: str = "") -> None: ...
    def set_latest(self, version_id: str) -> None: ...
    def set_status(self, version_id: str, status: bool) -> None: ...

__all__ = ["ProjectVersionRepository"]
