"""Auth 域仓储接口。"""
from typing import Optional, Protocol

class AuthRepository(Protocol):
    """认证仓储接口。"""
    def authenticate(self, username: str, password: str) -> Optional[dict]: ...
    def create_session(self, user_id: str, **kwargs) -> dict: ...
    def get_session_user(self, token: str) -> Optional[dict]: ...
    def delete_session(self, token: str) -> bool: ...
    def list_users(self, search: str = "", limit: int = 50) -> list: ...
    def create_user(self, username: str, password: str, **kwargs) -> dict: ...
    def get_user_by_id(self, user_id: str) -> Optional[dict]: ...
    def update_user(self, user_id: str, **kwargs) -> Optional[dict]: ...
    def delete_user(self, user_id: str) -> bool: ...
    def reset_password(self, user_id: str, new_password: str) -> bool: ...
    def set_user_enabled(self, user_id: str, enabled: bool) -> bool: ...

__all__ = ["AuthRepository"]
