"""项目应用配置聚合仓储接口。"""
from __future__ import annotations

from typing import Any, Dict, List, Protocol


class ProjectAppConfigRepository(Protocol):
    """项目应用配置仓储契约。"""
    def get_module_config(self, project_id: str, module: str) -> Dict[str, Any]: ...
    def save_module_config(self, project_id: str, module: str, config: Dict[str, Any]) -> Dict[str, Any]: ...
    def get_config_value(self, project_id: str, module: str, config_key: str, default: str = "") -> str: ...
    def set_config_value(self, project_id: str, module: str, config_key: str, value: Any) -> None: ...
    def get_all_modules(self, project_id: str = "") -> List[Dict[str, Any]]: ...

__all__ = ["ProjectAppConfigRepository"]
