"""用例评审聚合仓储接口（Repository Port）。

仅在 domain 层定义、由 infrastructure 实现。应用层依赖此接口而非
具体实现，便于测试替换（内存仓储）与多存储切换。仓储粒度为"聚合"：
CaseReview（评审头 + 关联用例）作为一个整体被读取/保存。
"""
from __future__ import annotations

from typing import List, Optional, Protocol, Tuple

from app.domain.case_review.domain.entities.case_review import CaseReview


class CaseReviewRepository(Protocol):
    """用例评审聚合仓储契约。"""

    def next_id(self) -> str: ...

    def save(self, review: CaseReview) -> CaseReview: ...

    def update(self, review: CaseReview) -> bool: ...

    def find_by_id(self, review_id: str) -> Optional[CaseReview]: ...

    def soft_delete(self, review_id: str, operator: str = "system") -> bool: ...

    def copy(self, source_id: str, new_name: str = "",
             operator: str = "system") -> Optional[CaseReview]: ...

    def link_cases(self, review_id: str, case_ids: List[str]) -> int: ...

    def unlink_cases(self, review_id: str, case_ids: List[str]) -> int: ...

    def update_link_status(self, review_id: str, case_ids: List[str],
                           result: str, reviewer: str = "",
                           comment: str = "") -> int: ...

    def list(self, *, keyword: str = "", project_id: str = "",
             status: str = "", limit: int = 500,
             offset: int = 0) -> Tuple[List[CaseReview], int]: ...

    def list_link_case_ids(self, review_id: str) -> set: ...

    def list_links(self, review_id: str) -> list: ...

    def get_status_counts(self, review_id: str) -> dict: ...

    def is_following(self, review_id: str, user_id: str) -> bool: ...

    def toggle_follow(self, review_id: str, user_id: str) -> bool: ...

    def count_by_module(self, project_id: str = "") -> dict: ...
