"""项目管理聚合仓储接口（Repository Port）。

仅在 domain 层定义、由 infrastructure 实现。应用层依赖此接口而非具体
实现，从而保持领域/应用层对存储的零依赖，便于测试替换（内存仓储）与
多存储切换。仓储粒度为"聚合"：Project 及其成员作为一个整体被读取/保存，
保证事务一致性（底层由既有四层 ProjectRepo 落库）。
"""
from __future__ import annotations

from typing import List, Optional, Protocol, Tuple

from app.domain.project.domain.entities.project import Project


class ProjectRepository(Protocol):
    """项目聚合仓储契约。"""

    def next_id(self) -> str: ...

    def save(self, project: Project) -> Project: ...

    def update(self, project: Project) -> Optional[Project]: ...

    def find_by_id(self, project_id: str, include_deleted: bool = False) -> Optional[Project]: ...

    def soft_delete(self, project_id: str) -> bool: ...

    def restore(self, project_id: str) -> bool: ...

    def list_projects(self, *, search: str = "", status: str = "", limit: int = 100,
                      include_deleted: bool = False) -> Tuple[List[Project], int]: ...

    def add_member(self, project_id: str, member: dict) -> Optional[dict]: ...

    def get_member(self, member_id: str) -> Optional[dict]: ...

    def list_members(self, project_id: str, keyword: str = "") -> List[dict]: ...

    def update_member(self, member_id: str, data: dict) -> Optional[dict]: ...

    def remove_member(self, project_id: str, user_id: str) -> bool: ...

    def batch_remove_members(self, project_id: str, user_ids: list) -> int: ...

    # ── 自定义函数（custom_funcs）旁路覆盖 ─────────────────
    def list_custom_funcs(self, project_id: str = "", keyword: str = "") -> List[dict]: ...

    def get_custom_func_row(self, func_id: str) -> Optional[dict]: ...

    def create_custom_func(self, func_id: str, name: str = "", script: str = "",
                           func_type: str = "HTTP", description: str = "",
                           status: str = "DRAFT", project_id: str = "",
                           tags: Optional[list] = None, params: str = "[]",
                           result: str = "", create_user: str = "admin") -> bool: ...

    def update_custom_func(self, func_id: str, updates: dict,
                           update_user: str = "admin") -> bool: ...

    def update_custom_func_status(self, func_id: str, status: str) -> bool: ...

    def delete_custom_func(self, func_id: str) -> bool: ...

    def list_custom_func_status(self, project_id: str = "") -> List[dict]: ...

    # ── 自定义字段（project_custom_fields）旁路覆盖 ────────
    def list_custom_fields(self, scope_id: str, scene: str = "") -> List[dict]: ...

    def get_custom_field(self, field_id: str) -> Optional[dict]: ...

    def upsert_custom_field(self, field_id: str, body: dict) -> Optional[dict]: ...

    def delete_custom_field(self, field_id: str) -> bool: ...
