"""资源池聚合仓储接口。"""
from __future__ import annotations

from typing import List, Optional, Protocol

from app.domain.resource_pool.domain.entities.resource_pool import ResourcePool


class ResourcePoolRepository(Protocol):
    def next_id(self) -> str: ...
    def save(self, pool: ResourcePool) -> ResourcePool: ...
    def get(self, pool_id: str) -> Optional[ResourcePool]: ...
    def list(self, keyword: str = "") -> List[ResourcePool]: ...
    def delete(self, pool_id: str) -> bool: ...
    def set_enable(self, pool_id: str, enable: bool) -> bool: ...

__all__ = ["ResourcePoolRepository"]
