"""统一 Repository 接口（Phase D · 存储层抽象）。

为各业务域的数据访问定义统一协议：
  - ApitestRepository: 接口测试域（合并 apitest / api_testing 两套实现）
  - BaseRepo 已有统一 CRUD 基础；此接口补充「按域」的语义契约。

用法：
  - 新代码面向接口（依赖 Protocol）编写，不直接 import 旧 store。
  - 各域 Repository（如 ApitestRepo）需显式实现对应 Protocol。
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional, Protocol, runtime_checkable


# ═══════════════════════════════════════════════════════
# 通用 CRUD 协议（BaseRepo 对齐）
# ═══════════════════════════════════════════════════════
@runtime_checkable
class CrudRepositoryProtocol(Protocol):
    """通用 CRUD 数据访问协议。"""

    table_name: str
    db_name: str

    def get_by_id(self, record_id: Any, id_col: str = "id") -> Optional[dict]: ...
    def query_one(self, sql: str, params: tuple = ()) -> Optional[dict]: ...
    def query_all(self, sql: str, params: tuple = ()) -> List[dict]: ...
    def execute(self, sql: str, params: tuple = ()) -> Any: ...
    def insert(self, data: dict) -> int: ...
    def update(self, record_id: Any, data: dict, id_col: str = "id") -> bool: ...
    def delete(self, record_id: Any, id_col: str = "id") -> bool: ...
    def count(self, where: str = "", params: tuple = ()) -> int: ...


# ═══════════════════════════════════════════════════════
# 接口测试域统一接口
# ═══════════════════════════════════════════════════════
class ApitestRepositoryProtocol(Protocol):
    """接口测试域 Repository 统一协议。

    合并 apitest.store 与 api_testing.management 两套实现。
    本协议描述该域公开能力的最小契约：
      - 定义 / 用例 / 场景 / Mock / 环境 / 回收站 的 CRUD
      - 执行与统计
      - 模块树 / 导入导出 / 关注 / 日志
    """

    # ── 接口定义 ─────────────────────────────────────
    def list_definitions(self, keyword: str = "", limit: int = 100,
                         offset: int = 0, project_id: str = "",
                         include_latest_only: bool = True) -> list: ...
    def count_definitions(self, project_id: str = "", **kwargs) -> int: ...
    def get_definition(self, definition_id: str) -> Optional[dict]: ...
    def create_definition(self, **kwargs) -> dict: ...
    def update_definition(self, definition_id: str, **kwargs) -> Optional[dict]: ...
    def delete_definition(self, definition_id: str) -> bool: ...

    # ── 版本 ─────────────────────────────────────────
    def list_definition_versions(self, ref_id: str) -> list: ...
    def create_definition_version(self, definition_id: str,
                                  version: str = "") -> Optional[dict]: ...
    def rollback_definition(self, definition_id: str,
                            version_id: str) -> Optional[dict]: ...

    # ── 接口用例 ─────────────────────────────────────
    def list_api_cases(self, keyword: str = "", limit: int = 100,
                       offset: int = 0, project_id: str = "", **kwargs) -> list: ...
    def count_api_cases(self, project_id: str = "", **kwargs) -> int: ...
    def get_api_case(self, case_id: str) -> Optional[dict]: ...
    def create_api_case(self, **kwargs) -> dict: ...
    def update_api_case(self, case_id: str, **kwargs) -> Optional[dict]: ...
    def delete_api_case(self, case_id: str) -> bool: ...

    # ── 场景 ─────────────────────────────────────────
    def list_scenarios(self, keyword: str = "", limit: int = 100,
                       offset: int = 0, project_id: str = "", **kwargs) -> list: ...
    def count_scenarios(self, project_id: str = "", **kwargs) -> int: ...
    def get_scenario(self, scenario_id: str) -> Optional[dict]: ...
    def create_scenario(self, **kwargs) -> dict: ...
    def update_scenario(self, scenario_id: str, **kwargs) -> Optional[dict]: ...
    def delete_scenario(self, scenario_id: str) -> bool: ...

    # ── Mock ─────────────────────────────────────────
    def list_mocks(self, keyword: str = "", limit: int = 100,
                   offset: int = 0, project_id: str = "", **kwargs) -> list: ...
    def count_mocks(self, project_id: str = "", **kwargs) -> int: ...
    def get_mock(self, mock_id: str) -> Optional[dict]: ...
    def create_mock(self, **kwargs) -> dict: ...
    def update_mock(self, mock_id: str, **kwargs) -> Optional[dict]: ...
    def delete_mock(self, mock_id: str) -> bool: ...

    # ── 环境 ─────────────────────────────────────────
    def list_environments(self, keyword: str = "", limit: int = 100,
                          project_id: str = "", **kwargs) -> list: ...
    def count_environments(self, project_id: str = "", **kwargs) -> int: ...
    def get_environment(self, env_id: str) -> Optional[dict]: ...
    def create_environment(self, **kwargs) -> dict: ...
    def update_environment(self, env_id: str, **kwargs) -> Optional[dict]: ...
    def delete_environment(self, env_id: str) -> bool: ...

    # ── 回收站 ───────────────────────────────────────
    def list_trash_definitions(self, project_id: str = "",
                               limit: int = 100) -> list: ...
    def restore_definition(self, definition_id: str) -> bool: ...
    def purge_definition(self, definition_id: str) -> bool: ...
    def list_trash_cases(self, project_id: str = "", limit: int = 100) -> list: ...
    def restore_case(self, case_id: str) -> bool: ...
    def purge_case(self, case_id: str) -> bool: ...
    def list_trash_scenarios(self, project_id: str = "",
                             limit: int = 100) -> list: ...
    def restore_scenario(self, scenario_id: str) -> bool: ...
    def purge_scenario(self, scenario_id: str) -> bool: ...
    def list_trash_mocks(self, project_id: str = "", limit: int = 100) -> list: ...
    def restore_mock(self, mock_id: str) -> bool: ...
    def purge_mock(self, mock_id: str) -> bool: ...

    # ── 执行与统计 ───────────────────────────────────
    def dashboard_stats(self) -> dict: ...
    def run_case(self, case_id: str, environment_id: str = "") -> dict: ...
    def run_scenario(self, scenario: dict, environment_id: str = "") -> dict: ...

    # ── 模块树 ───────────────────────────────────────
    def build_module_tree(self, module_type: str = "api",
                          include_api: bool = True,
                          project_id: str = "", **kwargs) -> list: ...
    def add_module(self, scope: str = "definition", name: str = "",
                   parent_id: str = "root", project_id: str = "",
                   module_type: str = "", **kwargs) -> dict: ...

    # ── 执行日志 ─────────────────────────────────────
    def list_execution_logs(self, exec_type: str = "", target_id: str = "",
                            limit: int = 100, offset: int = 0,
                            keyword: str = "") -> list: ...
    def count_execution_logs(self, exec_type: str = "",
                             target_id: str = "", keyword: str = "") -> int: ...
    def clear_execution_logs(self, exec_type: str = "") -> int: ...


# ═══════════════════════════════════════════════════════
# 抽象 Repository 基类（可选继承，也可仅实现 Protocol）
# ═══════════════════════════════════════════════════════
class BaseRepository(ABC):
    """抽象 Repository 基类。

    各域 Repository 可继承本类 + 实现对应 Protocol。
    本类保证统一连接入口与幂等建表能力。
    """

    # 子类必须指定
    db_name: str = "tga.db"
    table_name: str = ""

    @property
    def conn(self):
        """统一从 Database 连接池获取连接。"""
        from app.core.database import Database
        return Database.get_conn(self.db_name)

    @abstractmethod
    def ensure_table(self) -> None:
        """确保表结构存在（幂等）。"""
        ...


# ═══════════════════════════════════════════════════════
# 域 Repository 注册表（统一出口）
# ═══════════════════════════════════════════════════════
# {域: Repository 类/实例}
# 用于在启动或测试时验证「每域只保留一个数据出口」。
DOMAIN_REPOSITORIES: Dict[str, Any] = {}


def register_domain_repository(domain: str, repo: Any) -> None:
    """注册域 Repository，供统一出口查询。"""
    DOMAIN_REPOSITORIES[domain] = repo


def get_domain_repository(domain: str) -> Any:
    """获取域 Repository 实例。"""
    return DOMAIN_REPOSITORIES.get(domain)


__all__ = [
    "BaseRepository",
    "ApitestRepositoryProtocol",
    "CrudRepositoryProtocol",
    "register_domain_repository",
    "get_domain_repository",
    "DOMAIN_REPOSITORIES",
]
